export default {
  disclaimer: '',
  introduction: '',
  welshcorgicoin: 'Welsh Corgi Coin',
  buywelsh: 'Buy Welsh',
  community: 'Community Tokens',
  exchange: 'Welsh Street',
  lge: 'Liquidity Generation Event',
  tokenomics: 'Tokenomics',
  roadmap: 'Roadmap',
  security: 'Security Audit',
  privacy: '',
  risk: '',
  terms: '',
}
